# Generated by Django 5.0.4 on 2024-04-14 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=11)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
